// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AspNetCoreAssessment.Entities
{

    public partial class Student
    {

        public int Id { get; set; }
        public string Ssn { get; set; }
        public string Photo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

        public string PhoneNumber { get; set; }
        public DateTime Birthday { get; set; }
        public int Stage { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
        public int Gender { get; set; }

        public virtual Gender GenderNavigation { get; set; }
        public virtual Stage StageNavigation { get; set; }
    }
}